// The writer: scaffolds a Specline repo (init) and regenerates generated artifacts
// (sync). It writes generated files (folder READMEs, the workflow) and one-time
// scaffold starters (architecture.md, the pin). It NEVER overwrites an
// authored file — a generated file is recognized by its header; anything else is
// off-limits.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { LineCounter, isMap, isScalar, parseDocument } from "yaml";
import {
  FOLDER_DOCS, SCAFFOLD_FOLDERS, renderReadme, renderDocsReadme, isGenerated,
  docArchitecture, architectureMd, githubWorkflow, speclineYml, specTemplate,
} from "./content.ts";
import { InputError, resolveRepoRoot } from "../engine/model.ts";
import { CANON_MM } from "../version.ts";

export type FileKind = "generated" | "scaffold";
export type Action = "create" | "update" | "skip-authored" | "skip-exists" | "ok";

interface Planned { rel: string; content: string; kind: FileKind; }
export interface Outcome { rel: string; action: Action; }
export interface RunResult { outcomes: Outcome[]; clean: boolean; wrote: boolean; }

export interface InitOptions { decider: string; githubAction: boolean; check: boolean; }
export interface SyncOptions { check: boolean; }

function planInit(opts: InitOptions): Planned[] {
  const folders = SCAFFOLD_FOLDERS;
  const plan: Planned[] = folders.map((f) => ({ rel: `docs/${f}/README.md`, content: renderReadme(f), kind: "generated" as const }));
  plan.push({ rel: "docs/README.md", content: renderDocsReadme(folders), kind: "generated" });
  plan.push({ rel: "specline.yml", content: speclineYml(opts.decider), kind: "scaffold" });
  plan.push({ rel: "docs/architecture.md", content: architectureMd(), kind: "scaffold" });
  plan.push({ rel: "docs/conventions/doc-architecture.md", content: docArchitecture(opts.decider), kind: "scaffold" });
  plan.push({ rel: "docs/conventions/spec-template.md", content: specTemplate(opts.decider), kind: "scaffold" });
  if (opts.githubAction) plan.push({ rel: ".github/workflows/specline.yml", content: githubWorkflow(), kind: "generated" });
  return plan;
}

function planSync(root: string): Planned[] {
  const plan: Planned[] = [];
  const present = Object.keys(FOLDER_DOCS).filter((f) => existsSync(join(root, "docs", f)));
  if (existsSync(join(root, "docs"))) {
    plan.push({ rel: "docs/README.md", content: renderDocsReadme(present), kind: "generated" });
  }
  for (const f of present) {
    plan.push({ rel: `docs/${f}/README.md`, content: renderReadme(f), kind: "generated" });
  }
  if (existsSync(join(root, ".github/workflows/specline.yml"))) {
    plan.push({ rel: ".github/workflows/specline.yml", content: githubWorkflow(), kind: "generated" });
  }
  return plan;
}

function evaluate(abs: string, p: Planned): Action {
  const exists = existsSync(abs);
  if (p.kind === "scaffold") return exists ? "skip-exists" : "create";
  if (!exists) return "create";
  const cur = readFileSync(abs, "utf8");
  if (!isGenerated(cur)) return "skip-authored";
  return cur === p.content ? "ok" : "update";
}

function run(root: string, plan: Planned[], check: boolean): RunResult {
  const outcomes: Outcome[] = [];
  let clean = true;
  let wrote = false;
  for (const p of plan) {
    const abs = join(root, p.rel);
    const action = evaluate(abs, p);
    if (action === "create" || action === "update") clean = false;
    if (!check && (action === "create" || action === "update")) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, p.content);
      wrote = true;
    }
    outcomes.push({ rel: p.rel, action });
  }
  return { outcomes, clean, wrote };
}

export function init(root: string, opts: InitOptions): RunResult {
  if (typeof opts.decider !== "string" || opts.decider.trim() === "") throw new InputError("decider must be a non-empty name");
  return run(root, planInit(opts), opts.check);
}

export function sync(root: string, opts: SyncOptions): RunResult {
  root = resolveRepoRoot(root); // sync regenerates a repo's docs; there must be one
  return run(root, planSync(root), opts.check);
}

// The two authored files that carry the canon pin. They are scaffolded once and
// never regenerated by sync, so a canon bump leaves them stale — `upgrade` is the
// sanctioned way to rewrite just the version token in each, in place.
const PIN_REWRITES: { rel: string; re: RegExp; replace: string }[] = [
  {
    rel: "docs/conventions/doc-architecture.md",
    re: /(\*\*Canon\*\*\s*\|\s*Specline\s*`?)[0-9][^`\s|]*/,
    replace: `$1${CANON_MM}`,
  },
];

/** "3.1.0-draft" -> "3.1". A repo pin tracks MAJOR.MINOR, which is also the grain
 *  CANON-PIN-MISMATCH compares at — so a canon patch must not churn every repo. */
function majorMinor(v: string): string | null {
  const m = v.trim().replace(/^v/i, "").match(/^(\d+)\.(\d+)/);
  return m ? `${m[1]}.${m[2]}` : null;
}

/** Drop the v3.0 `| **Tier** |` row. Tiers are gone (canon 3.1), and a stale row is
 *  worse than none: it tells a reader the repo is configured by something inert. */
function dropTierRow(cur: string): string {
  const eol = cur.includes("\r\n") ? "\r\n" : "\n";
  const lines = cur.split(/\r?\n/).filter((l) => !/^\s*\|\s*\*\*Tier\*\*\s*\|/.test(l));
  return lines.join(eol);
}

/** Migrate the v3.0 `tier:` key. `tier: 2` was "governance", which is what the
 *  unattended switch now means, so it maps across; `tier: 0|1` differed only in
 *  whether knowledge/ and archive/ existed, and the record's rules only fire on
 *  folders that exist — so the line carried no information and is dropped. The
 *  rewrite is located by the YAML parser and applied to that one line, so inline
 *  comments, key order, quoting style and line endings survive. */
function migrateTier(cur: string): string {
  const lineCounter = new LineCounter();
  const doc = parseDocument(cur, { schema: "failsafe", lineCounter, prettyErrors: false });
  if (doc.errors.length > 0) throw new InputError(`specline.yml: ${doc.errors[0]!.message}`);
  if (!isMap(doc.contents)) throw new InputError("specline.yml must be a `key: value` mapping");
  const pair = doc.contents.items.find((i) => isScalar(i.key) && i.key.value === "tier");
  if (pair === undefined) return cur;
  if (!isScalar(pair.value) || typeof pair.value.value !== "string" || !isScalar(pair.key) || !pair.key.range) {
    throw new InputError("specline.yml tier must be a scalar value");
  }
  const eol = cur.includes("\r\n") ? "\r\n" : "\n";
  const lines = cur.split(/\r?\n/);
  const at = lineCounter.linePos(pair.key.range[0]).line - 1;
  const already = doc.get("unattended", true) !== undefined && doc.get("unattended", true) !== null;
  if (pair.value.value === "2" && !already) {
    lines[at] = lines[at]!.replace(/tier:[^\S\r\n]*("?)2\1/, "unattended: true");
  } else {
    lines.splice(at, 1);
  }
  return lines.join(eol);
}

/** Rewrite (or add) `canon:` in a specline.yml, changing nothing else. A regex
 *  rewrite of the value stripped the quotes off `canon: "2.4.0"`; splicing over
 *  the scalar's own source range preserves the quoting style, inline comments,
 *  key order and line endings exactly. */
function rewritePin(cur: string): string {
  const doc = parseDocument(cur, { schema: "failsafe", prettyErrors: false });
  if (doc.errors.length > 0) throw new InputError(`specline.yml: ${doc.errors[0]!.message}`);
  if (!isMap(doc.contents)) throw new InputError("specline.yml must be a `key: value` mapping");
  const pin = doc.get("canon", true);
  if (pin === undefined || pin === null) {
    // No pin at all: the repo claims no canon, which `upgrade` exists to fix.
    const eol = cur.includes("\r\n") ? "\r\n" : "\n";
    const lines = cur.split(/\r?\n/);
    const at = lines.findIndex((l) => l.trim() !== "" && !l.trimStart().startsWith("#"));
    lines.splice(at === -1 ? lines.length : at, 0, `canon: ${CANON_MM}`);
    return lines.join(eol);
  }
  if (!isScalar(pin) || typeof pin.value !== "string" || !pin.range) {
    throw new InputError("specline.yml canon must be a version string");
  }
  // Already tracking this canon at MAJOR.MINOR: leave the author's exact string alone.
  if (majorMinor(pin.value) === CANON_MM) return cur;
  const quoted = pin.type === "QUOTE_DOUBLE" ? JSON.stringify(CANON_MM) : pin.type === "QUOTE_SINGLE" ? `'${CANON_MM}'` : CANON_MM;
  return cur.slice(0, pin.range[0]) + quoted + cur.slice(pin.range[1]);
}

/** Bring a repo to the canon this tool serves: migrate the config, rewrite the pin in
 *  specline.yml and doc-architecture.md, then regenerate the generated files (same as
 *  sync). One step, so a pin bump and the generated headers can never drift apart. */
export function upgrade(root: string, opts: SyncOptions): RunResult {
  root = resolveRepoRoot(root);
  const outcomes: Outcome[] = [];
  let clean = true;
  let wrote = false;

  const yml = join(root, "specline.yml");
  if (existsSync(yml)) {
    const cur = readFileSync(yml, "utf8");
    const next = rewritePin(migrateTier(cur));
    if (next === cur) {
      outcomes.push({ rel: "specline.yml", action: "ok" });
    } else {
      clean = false;
      if (!opts.check) {
        writeFileSync(yml, next);
        wrote = true;
      }
      outcomes.push({ rel: "specline.yml", action: "update" });
    }
  }

  for (const pin of PIN_REWRITES) {
    const abs = join(root, pin.rel);
    if (!existsSync(abs)) continue; // no pin to bump here
    const cur = readFileSync(abs, "utf8");
    const next = dropTierRow(cur.replace(pin.re, pin.replace));
    if (next === cur) {
      outcomes.push({ rel: pin.rel, action: "ok" });
      continue;
    }
    clean = false;
    if (!opts.check) {
      writeFileSync(abs, next);
      wrote = true;
    }
    outcomes.push({ rel: pin.rel, action: "update" });
  }

  // regenerate generated artifacts so headers track the new canon too
  const gen = run(root, planSync(root), opts.check);
  outcomes.push(...gen.outcomes);
  clean &&= gen.clean;
  wrote ||= gen.wrote;
  return { outcomes, clean, wrote };
}
