#!/usr/bin/env node
// Regenerate the bundled canon (cli/canon/) from the source canon at the monorepo
// root. The bundle is a BUILD ARTIFACT — never hand-edited — so this script is the
// only sanctioned way to update it.
//
//   node scripts/sync-canon.mjs           # copy source -> bundle
//   node scripts/sync-canon.mjs --check   # exit 1 if bundle != source (release/CI gate)
//   node scripts/sync-canon.mjs --source <dir>   # override the source repo dir
//
// Canon and cli now live in one repo, so the --check gate runs in normal CI: the
// source canon is always at the repo root, one level above cli/.

import { readFileSync, readdirSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const args = process.argv.slice(2);
const check = args.includes("--check");
const srcIdx = args.indexOf("--source");
const bundleDir = fileURLToPath(new URL("../canon/", import.meta.url));
const embedPath = fileURLToPath(new URL("../src/canon-bundle.ts", import.meta.url));
const sourceDir = srcIdx !== -1 && args[srcIdx + 1]
  ? args[srcIdx + 1]
  : fileURLToPath(new URL("../../", import.meta.url));

// The embedded copy: a generated TS module so a compiled single-file binary
// (`bun --compile`) can serve the canon with no `canon/` file on disk. Source and
// Action runs read `canon/` directly; this is the fallback (see src/canon.ts).
const embedModule = (name, text) =>
  `// GENERATED by scripts/sync-canon.mjs — do not edit. Embeds the bundled canon so a\n` +
  `// compiled binary can serve it offline; source/Action runs read canon/ from disk.\n` +
  `export const BUNDLED_CANON_FILE = ${JSON.stringify(name)};\n` +
  `export const BUNDLED_CANON_TEXT = ${JSON.stringify(text)};\n`;

const onlyCanon = (dir) => readdirSync(dir).filter((f) => /^specline-.*\.md$/.test(f));

const sourceFiles = onlyCanon(sourceDir);
if (sourceFiles.length !== 1) {
  console.error(`sync-canon: expected exactly one specline-*.md in ${sourceDir}, found ${sourceFiles.length}`);
  process.exit(2);
}
const sourceName = sourceFiles[0];
const sourceText = readFileSync(join(sourceDir, sourceName), "utf8");

if (check) {
  const bundled = onlyCanon(bundleDir);
  const fileOk = bundled.length === 1 && bundled[0] === sourceName
    && readFileSync(join(bundleDir, bundled[0]), "utf8") === sourceText;
  let embedOk = false;
  try { embedOk = readFileSync(embedPath, "utf8") === embedModule(sourceName, sourceText); } catch { embedOk = false; }
  if (!fileOk || !embedOk) {
    const what = !fileOk ? `bundle (${bundled.join(", ") || "none"})` : "embedded canon-bundle.ts";
    console.error(`sync-canon: DRIFT — ${what} != source (${sourceName}). Run: npm run sync-canon`);
    process.exit(1);
  }
  console.log(`sync-canon: bundle + embed match source (${sourceName}) ✓`);
  process.exit(0);
}

for (const f of onlyCanon(bundleDir)) rmSync(join(bundleDir, f));
writeFileSync(join(bundleDir, sourceName), sourceText);
writeFileSync(embedPath, embedModule(sourceName, sourceText));
console.log(`sync-canon: bundled ${sourceName} (${sourceText.length} bytes) + embedded canon-bundle.ts from ${sourceDir}`);
