// The bundled canon. The cli ships a verbatim copy of the canon under `canon/`
// so `doctor spec` and the MCP `doctor_spec` tool can serve it offline, version-
// locked to the binary. The copy is a BUILD ARTIFACT, not a second original:
// `scripts/sync-canon.mjs` regenerates it from the source repo, and the version
// is read FROM the file here rather than hand-typed — so the filename, the
// served text, and the reported version can never drift apart.
//
// Two run modes:
//   - Source / Action / `node`: the `canon/` dir is on disk → read it (the path below).
//   - Compiled single-file binary (`bun --compile`): there is no `canon/` on disk, so
//     we fall back to the embedded copy in `canon-bundle.ts` (also generated by
//     sync-canon, and verified by `--check`, so it can't drift from the file).

import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { BUNDLED_CANON_FILE, BUNDLED_CANON_TEXT } from "./canon-bundle.ts";

export interface BundledCanon {
  /** the full canon markdown. */
  text: string;
  /** the canon version, parsed from the `**Canon version:**` line. */
  version: string;
  /** absolute path to the bundled file, or `embedded:<name>` in a compiled binary. */
  path: string;
}

let cached: BundledCanon | null = null;

function parseVersion(text: string, label: string): string {
  const m = text.match(/\*\*Canon version:\*\*\s*(\d+\.\d+\.\d+(?:-[a-z0-9]+(?:\.[a-z0-9]+)*)?)/i);
  if (m === null) throw new Error(`bundled canon ${label} has no "**Canon version:**" line`);
  return m[1]!;
}

/** Read the bundled canon from disk. Returns null only when the `canon/` dir is
 *  absent (a compiled binary); a present-but-malformed bundle still throws, so a
 *  packaging error in a source/Action run is never masked by the embedded fallback. */
function readFromDisk(): BundledCanon | null {
  const dir = fileURLToPath(new URL("../canon/", import.meta.url));
  let files: string[];
  try {
    files = readdirSync(dir).filter((f) => /^specline-.*\.md$/.test(f));
  } catch {
    return null; // no canon/ on disk → compiled binary; use the embedded copy
  }
  if (files.length !== 1) {
    throw new Error(`expected exactly one bundled canon in canon/, found ${files.length} (${files.join(", ") || "none"})`);
  }
  const path = join(dir, files[0]!);
  const text = readFileSync(path, "utf8");
  return { text, version: parseVersion(text, files[0]!), path };
}

/** Resolve the single bundled canon (disk, else the embedded copy). */
export function loadCanon(): BundledCanon {
  if (cached !== null) return cached;
  cached = readFromDisk() ?? {
    text: BUNDLED_CANON_TEXT,
    version: parseVersion(BUNDLED_CANON_TEXT, BUNDLED_CANON_FILE),
    path: `embedded:${BUNDLED_CANON_FILE}`,
  };
  return cached;
}
